FROM php:8.2-fpm

RUN apt update && apt install -y libicu-dev zlib1g-dev libexif-dev libpng-dev libjpeg-dev libxml2-dev libzip-dev libxslt-dev libldap-dev locales && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-configure gd --with-jpeg
RUN docker-php-ext-install pdo pdo_mysql mysqli exif gd soap intl zip xsl opcache ldap
RUN pecl install -o -f redis &&  rm -rf /tmp/pear &&  docker-php-ext-enable redis
# RUN pecl install xdebug && docker-php-ext-enable xdebug
#RUN localedef -c -i en_AU -f UTF-8 en_AU.UTF-8
RUN localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8
 
COPY --from=composer/composer:latest-bin /composer /usr/bin/composer
RUN composer self-update

RUN useradd -u 1000 cb
#RUN usermod -u 1000 www-data