ARG PHP_VERSION="8.4"
FROM php:${PHP_VERSION}-fpm

RUN apt update && apt install -y libicu-dev libpq-dev zlib1g-dev libexif-dev libpng-dev libjpeg-dev libxml2-dev libzip-dev libxslt-dev libldap-dev locales && rm -rf /var/lib/apt/lists/*

#RUN docker-php-ext-configure gd --with-jpeg
#RUN docker-php-ext-install pdo pdo_mysql pgsql pdo_pgsql  mysqli exif gd soap intl zip xsl opcache ldap

RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install pgsql pdo_pgsql
RUN docker-php-ext-install exif
RUN docker-php-ext-configure gd --with-jpeg
RUN docker-php-ext-install gd
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install opcache
RUN docker-php-ext-install soap
RUN docker-php-ext-configure zip
RUN docker-php-ext-install zip
RUN docker-php-ext-install xsl

RUN pecl install channel://pecl.php.net/xmlrpc-1.0.0RC3
RUN docker-php-ext-enable xmlrpc

# Configure PHP to use msmtp for mail()
#RUN echo "sendmail_path = /usr/bin/msmtp -t" >> /usr/local/etc/php/conf.d/sendmail.ini

# Redis
RUN pecl install -o -f redis \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis

# RUN pecl install xdebug && docker-php-ext-enable xdebug
#RUN localedef -c -i en_AU -f UTF-8 en_AU.UTF-8
#RUN localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8

# Generate locales from LOCALES env variable
# RUN for locale in $LOCALES; do \
#     sed -i -e "s/# $locale/$locale/" /etc/locale.gen; \
#     done && \
#     locale-gen

ENV LANG=fr_FR.UTF-8
ENV LC_ALL=fr_FR.UTF-8

# Composer
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#RUN composer install --no-dev --classmap-authoritative

COPY --from=composer/composer:latest-bin /composer /usr/bin/composer
RUN composer self-update

#RUN useradd -u 1000 $USER
#RUN usermod -u 1000 www-data